apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: asia.gcr.io/vinid-devops/nginx:1.21.5-alpine
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: docker-image-pull-secret
